image: node:latest

pages:
  stage: deploy
  script:
  - npm install -g elm@latest-0.19.1 uglify-js --unsafe-perm=true --allow-root
  - make build
  artifacts:
    paths:
    - public
    expire_in: 3 mins # latest is always kept
  only:
  - master
